<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fku_sermon"
 *
 * Auto generated by Extension Builder 2014-06-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'FKU Sermon',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Widmer',
	'author_email' => 'daniel.widmer@fku.ch',
	'dependencies' => 'extbase,fluid',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.2.1',
	'constraints' => [
		'depends' => [
			'typo3' => '7.6.0 - 10.4.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
/***********************************************
 * Version 1.8.0
 * -------------                    
 * Charts not fixed on last 3 monthts but flexible
 *
 * Version 1.9.0
 * -------------                    
 * Specific user group defined in constants to admin sermons
 * By default a new sermon is not public
 *
 * Version 1.9.1
 * -------------                    
 * Headphones icon for mp3 files
 *
 * Version 1.9.2
 * -------------                    
 * Date format in Last.html
 *
 * Version 1.9.3
 * -------------                    
 * Added MIME type "application/octet-stream" for the headphone icon
 *
 * Version 1.9.4
 * -------------                    
 * Halflings instead of glyphicons
 *
 * Version 2.0.0
 * -------------                    
 * Ready for Typo3 8.7
 * Own formatting of FlashMassages
 * Notification rule at the time the sermon is set public
 *
 * Version 2.0.1
 * -------------                    
 * Field "recent" for serials to reduce length of dropdown list in new sermon form
 *
 * Version 2.0.2
 * -------------                    
 * Allow clickable links in sermon concept text by using own parseFunc_RTE_onlyLink setup
 *
 * Version 2.0.3
 * -------------                    
 * Separate role and adapted form for NewAction to only upload attachments
 *
 * Version 2.0.4
 * -------------                    
 * Minor changes in NewAction for only uploading attachments
 *
 * Version 2.1.0
 * -------------                    
 * Use ObjectStorage and FileReference FAL for related files (incl new model FileReference)
 * Update on alert partial, dismissible OK alert
 * Alert text if not suitable sermon was found
 * In forms for new and edit sermon, buttons are disabled during submit and spinner is shown
 * Uploaded files get standardized file names depending on the sermon's date
 *
 * Version 2.1.1
 * -------------                    
 * Corrections in TCA definitions in order to remove depraciated functions
 *
 * Version 3.0.0
 * -------------                    
 * Ready for Typo3 version 10, Bootstrap 4.5, and Glyphicons 2.4
 *
 * Version 3.0.1
 * -------------                    
 * Corrected typo in template Last.html
 * Correction in Model FileReferece.php
 *
 * Version 3.0.2
 * -------------                    
 * composer.json added
 * Minor correction in template List.html for the action to be called (sermonList -> list)
 *
 * Version 3.1.0
 * -------------                    
 * Added partial Sermon/Notes and use it in template List
 * Commented out the links for adding new sermons in template List
 * Modified setup.txt with template paths (instead of path)
 *
 * Version 3.2.0
 * -------------                    
 * Removed clearing of cache in controller
 * Newly defined plugins instead of swtichable controller action in flexform
 * Renaming extension of typoscript files 
 *
 * Version 3.2.1
 * -------------                    
 * Declared list view to be not cached in ext_emconf.php
 *
**/